title: Niklas Michl
# All commneted out can be found later
logo: /Style/foto.jpg
desription: Coding Projects in the Fields of Explanatory Data analysis, Time series analysis and database querys 

theme: jekyll-theme-minimal
