title: Niklas Michl
# All commneted out can be found later
#logo: Add Path here of an image. Need to be uploaded to github
# desription: Text below image (Data Science Portfolio)
# show_downloads: true
theme: jeykell-theme-minimal
